#!/usr/bin/env zsh

anormal_id="$(~/meta/zfuncs/hypr-activeworkspace-id)"
aspecial_id="special:special:0"
echo "$anormal_id, $aspecial_id"
if [[ "$(hyprctl activewindow | sed '6!d')" = *"special"* ]]
then
  hyprctl dispatch movetoworkspace "$anormal_id"
else
  hyprctl dispatch movetoworkspace "$aspecial_id"
fi
